---
- name: Set timezone to Asia/Shanghai
  file: src=/usr/share/zoneinfo/Asia/Shanghai
        dest=/etc/localtime
        state=link
        force=yes

- name: Update package list
  become: yes
  become_method: sudo
  apt: upgrade=dist update_cache=yes

- name: Install basic packages
  become: yes
  become_method: sudo
  apt: name={{ item }} state=latest
  with_items:
    - bash
    - build-essential
    - cscope
    - curl
    - fonts-powerline
    - git
    - htop
    - nmap
    - nodejs
    - npm
    - screen
    - tmux
    - vim
    - wget
    - zsh

- name: Install python 3
  become: yes
  become_method: sudo
  apt: name={{ item }} state=latest
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - python3-setuptools
    - python-pycurl

- name: Install the fuck
  become: yes
  become_method: sudo
  pip:
    name: thefuck
    executable: pip3

- name: Install FASD
  become: yes
  become_method: sudo
  copy: src=fasd dest=/usr/local/bin/fasd mode=755

- name: Install TL;DR
  npm:
    name: tldr
    global: yes
